### ISSUE TITLE
Supporting Java 17

### ISSUE THREAD

**Issue by aghasemi** [antkorwin/better-strings#21]
Hi, 

Currently, adding better-strings to the list of dependencies and running under Java 17 crashes with the following exception:

```


An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.IllegalAccessError: class com.antkorwin.betterstrings.BetterStringsProcessor (in unnamed module @0x49070868) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x49070868
 at com.antkorwin.betterstrings.BetterStringsProcessor.init(BetterStringsProcessor.java:41)
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:701)
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:828)
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:924)
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)
 at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)
 at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)
 at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)
 at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
 at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
 at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
 at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

May I ask if this is familiar, and how can I proceed to fix it? Googling the error yields [this issue page in Lombok repository](https://github.com/projectlombok/lombok/issues/2681), which has apparently been fixed for Java 16. Are these related?

Many thanks

**Comment by JJBRT** [comment]
Maybe [this answer](https://github.com/sshahine/JFoenix/issues/1200#issuecomment-926829467) can help you

**Comment by aghasemi** [comment]
It didn't work, unfortunately.
I am using [JBang](https://jbang.dev) for a basic script. Here is a minimal example:

```

///usr/bin/env jbang "$0" "$@" ; exit $?

//JAVA 17
//JAVA_OPTION --illegal-access=permit

//DEPS org.burningwave:core:9.4.1
//DEPS com.antkorwin:better-strings:0.5

public class BSExample {

   
    public static void main(String... args) {
        org.burningwave.core.assembler.StaticComponentContainer.JVMInfo.getVersion();
        var n=0;
        System.out.println("n is ${n}");

    }
}

```

You can run it using `jbang run BSExample.java`

**Comment by aghasemi** [comment]
Hi. Do we have any updates here?

**Comment by igrigorov** [comment]
Have you tried explicitly allowing the internal Java packages, used by Better Strings (see my answer in #22)?
I think that `--illegal-access=permit` is deprecated in Java 17.

**Comment by aghasemi** [comment]
Amazing! It worked. Many thanks.

Actually, it worked keeping only four of the modules you provided in compiler arguments. So here is the minimal JBang script for  anyone to try:

```java 
///usr/bin/env jbang "$0" "$@" ; exit $?

//JAVA 17
//JAVAC_OPTIONS -J--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED 	
//JAVAC_OPTIONS -J--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED	
//JAVAC_OPTIONS -J--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED 
//JAVAC_OPTIONS -J--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED


//DEPS com.antkorwin:better-strings:0.5

public class BS {

   
    public static void main(String... args) {
        
        var n=0;
        System.out.println("n is ${n}");

    }
}
```

**Comment by PawelLipski** [comment]
+1, although I've also needed to add opens for `com.sun.tools.javac.code`:

```kotlin
tasks.withType<JavaCompile> {
    options.isFork = true
    options.forkOptions.jvmArgs?.addAll(
      listOf(
        "--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
        "--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
        "--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED",
        "--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
        "--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"
      )
    )
}
```

**Comment by mkondratek** [comment]
+1, it would be nice to have it working correctly 🙂

**Comment by PawelLipski** [comment]
Note that apparently just `--add-exports` is enough, no need for the stronger `--add-opens`.
